name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install
      run: npm install

    - name: Compile
      run: npm run build

    - name: npm test
      run: npm run cy:run:Test2