name: Cypress Demp
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: npx cypress run --spec "cypress/integration/AutoCheckBillingTests/Running.spec.js
